### ISSUE TITLE
Generate JSON table schema?

### ISSUE THREAD

**Issue by harrisj** [timwis/csv-schema#2]
This is an awesome idea! But I was wondering if you might consider also adding support for generating a [JSON table schema file](http://dataprotocols.org/json-table-schema/) from the CSV. This is a format for writing schemas for CSV files in JSON that is supported by a few validators like [Good Tables](http://goodtables.okfnlabs.org/) and [CSVlint](http://csvlint.io/)

**Comment by timwis** [comment]
Hey @harrisj, thanks! I think that's a great idea, and was just chatting about it in #4. If it's all right, I'll close this issue in favor of consolidating the discussion there.
